databases:
  - name: OneTrip_DB
    databaseName: onetrip_db
    user: onetrip_user
    region: singapore

services:
  - type: web
    name: OneTrip
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: OneTrip_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

