databases:
  - name: one_trip_production
    databaseName: one_trip_production
    user: one_trip_user
    region: singapore

services:
  - type: web
    name: OneTrip
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: one_trip_production
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false

