databases:
  - name: One Trip
    databaseName: onetripdb
    user: onetripdb_user
    region: singapore

services:
  - type: web
    name: One Trip
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: onetripdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

