databases:
  - name: onetrip
    databaseName: onetrip
    user: onetrip_user
    region: singapore

services:
  - type: web
    name: onetrip
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: onetrip
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

